server:
  port: 80
  
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:./local
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: 
  datasource:
    url: jdbc:mysql://localhost:3306/penpal?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: keylink
    password: 1234


  jpa:
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#        show_sql: true
    hibernate:
      ddl-auto: update

logging:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

upload:
  path: C:/upload/
