server:
  port: 80
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./local
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format-sql: true
        show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate: info

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

upload:
  path: C:/upload/
